{
  "textPayload": "Traceback (most recent call last):\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 419, in run_asgi\n    result = await app(  # type: ignore[func-returns-value]\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py\", line 78, in __call__\n    return await self.app(scope, receive, send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/fastapi/applications.py\", line 271, in __call__\n    await super().__call__(scope, receive, send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/applications.py\", line 118, in __call__\n    await self.middleware_stack(scope, receive, send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/middleware/errors.py\", line 184, in __call__\n    raise exc\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/middleware/errors.py\", line 162, in __call__\n    await self.app(scope, receive, _send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/middleware/cors.py\", line 92, in __call__\n    await self.simple_response(scope, receive, send, request_headers=headers)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/middleware/cors.py\", line 147, in simple_response\n    await self.app(scope, receive, send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/middleware/exceptions.py\", line 79, in __call__\n    raise exc\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/middleware/exceptions.py\", line 68, in __call__\n    await self.app(scope, receive, sender)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py\", line 21, in __call__\n    raise e\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py\", line 18, in __call__\n    await self.app(scope, receive, send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/routing.py\", line 706, in __call__\n    await route.handle(scope, receive, send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/routing.py\", line 276, in handle\n    await self.app(scope, receive, send)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/starlette/routing.py\", line 66, in app\n    response = await func(request)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/fastapi/routing.py\", line 237, in app\n    raw_response = await run_endpoint_function(\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/fastapi/routing.py\", line 163, in run_endpoint_function\n    return await dependant.call(**values)\n  File \"/workspace/app/routers/session.py\", line 286, in update_session_time\n    doctor_calendar_pull = db.doctor.update_one(\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/collection.py\", line 1041, in update_one\n    self._update_retryable(\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/collection.py\", line 836, in _update_retryable\n    return self.__database.client._retryable_write(\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/mongo_client.py\", line 1476, in _retryable_write\n    return self._retry_with_session(retryable, func, s, None)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/mongo_client.py\", line 1349, in _retry_with_session\n    return self._retry_internal(retryable, func, session, bulk)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/_csot.py\", line 105, in csot_wrapper\n    return func(self, *args, **kwargs)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/mongo_client.py\", line 1390, in _retry_internal\n    return func(session, sock_info, retryable)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/collection.py\", line 817, in _update\n    return self._update(\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/collection.py\", line 782, in _update\n    _check_write_command_response(result)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/helpers.py\", line 217, in _check_write_command_response\n    _raise_last_write_error(write_errors)\n  File \"/layers/google.python.pip/pip/lib/python3.9/site-packages/pymongo/helpers.py\", line 190, in _raise_last_write_error\n    raise WriteError(error.get(\"errmsg\"), error.get(\"code\"), error)\npymongo.errors.WriteError: Cannot apply $pull to a non-array value, full error: {'index': 0, 'code': 2, 'errmsg': 'Cannot apply $pull to a non-array value'}",
  "insertId": "64fed5b5000e687048255506",
  "resource": {
    "type": "gae_app",
    "labels": {
      "version_id": "staging",
      "zone": "asia-south1-4",
      "module_id": "default",
      "project_id": "mobile-doc-backend"
    }
  },
  "timestamp": "2023-09-11T08:54:13.944240Z",
  "severity": "ERROR",
  "labels": {
    "clone_id": "00c61b117c8d3f93dc5c8709390112f6dd73afc1890b9961b87083439186af1cd101d0ad09a09c00a9a08394c0f758b7abc0a3c54a7b003bcee9"
  },
  "logName": "projects/mobile-doc-backend/logs/stderr",
  "receiveTimestamp": "2023-09-11T08:54:14.003953558Z"
}